# Generated by Django 3.1.1 on 2020-09-26 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('vote', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
                ('question', models.CharField(max_length=200)),
                ('isopen', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decision_maker.candidate')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decision_maker.criteria')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decision_maker.poll')),
            ],
        ),
        migrations.AddField(
            model_name='criteria',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decision_maker.poll'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decision_maker.poll'),
        ),
    ]
