# Generated by Django 3.1.1 on 2020-10-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_maker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='score',
            name='poll',
        ),
        migrations.AddField(
            model_name='poll',
            name='admin_code',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
